all:
	gcc	part1.c	-o	part1
	gcc     cse320_functions.c	test13.c	-o	main	-static	-lpthread
ec2:
	gcc     test2.c	EC2.c	-o	ec2	-static	-lpthread
ec13:
	gcc     test13.c	EC1and3.c	-o	ec13	-static	-lpthread
ec4:
	gcc     test4.c	EC4.c	-o	ec4	-static	-lpthread
clean:
	rm	-f	part1
	rm	-f	ec2
	rm	-f	ec13
	rm	-f	ec4

