part2:
	gcc	App1.c	-o	solver	-lm
	gcc	App2.c	-o	trace
	gcc	App3.c	-o	fib
	gcc	main.c	-o	part2
part3:
	gcc	wallet_stat.c	-o	part3	-g	
	gcc	print_help.o	-o 	print_help
ec:
	gcc	ECpart1.c	-o	ec
clean:
	rm	-f	solver
	rm	-f	trace
	rm	-f	fib
	rm	-f	part2
	rm	-f	part3
	rm	-f	print_help
	rm	-f	ec
